### ISSUE TITLE
Access to URL denied

### ISSUE THREAD

**Issue by mcwoojcik** [clovermini/WPU-Net#1]
Hello, I was trying to inference your solution for grain border detection but I'm not able to run main.py and data_generator.py because of acces denied to your sites:

I also tried to just copy and paste address into browser but the problem is the same (error 403). 

data_generator.py error output:

```
File "data_generator.py", line 15, in <module>
    download_from_url(url='https://doc-00-3k-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/51jfsmsfpjal1l3rob0i2p7t8eh1d2g3/1567137600000/03563112468744709654/*/1G0KekPURcOmVVnelMvkw_FF-75DMkmjo?e=download', filename=data_dir, save_dir=cwd)
  File "/home/kaczor/WPU-Net/segmentation/tools.py", line 35, in download_from_url
    file_path, _ = urllib.request.urlretrieve(url, None, _progress)
  File "/usr/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

main.py output (after adding empty required folders):
```
python main.py 
############## segmentation inference  ##############
Downloading ... 
Traceback (most recent call last):
  File "main.py", line 304, in <module>
    inference()
  File "main.py", line 43, in inference
    filename='wpu_net_parameters.zip', save_dir=os.path.join(cwd, 'segmentation'))
  File "/home/kaczor/WPU-Netttttt/segmentation/tools.py", line 35, in download_from_url
    file_path, _ = urllib.request.urlretrieve(url, None, _progress)
  File "/usr/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by mcwoojcik** [comment]
I suppose is the problem with access to your google drive...

**Comment by mamrez7** [comment]
I get the same error. Would you explain how to solve this?

**Comment by mcwoojcik** [comment]
Unfortunately, I wasn't able to solve it. It is necessary to have access to the required models stored in the author's google drive...

**Comment by clovermini** [comment]
Data download permissions have been opened, you can download it from https://github.com/Keep-Passion/pure_iron_grain_data_sets.
